services:
  - type: web
    name: steam-tracker-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: RUN_SCHEDULER
        value: "false"

  - type: background
    name: steam-tracker-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RUN_SCHEDULER
        value: "true"
